#!/bin/bash
clear
echo '--------------------------------------'
echo 'COPY TEKS INI UNTUK BANNER SSH PREMIUM'
echo '--------------------------------------'
echo '<font color="red">====SELAMAT DATANG DI @RAKA_ID====<br>##SSH KHUSUS PREMIUM##</font><br>
<font color="green">====================================</font><br>
<font color="magenta">DOWNLOAD CONFIG TER-UPDATE HANYA DI www.raka-id.xyz</font><br>
<font color="green">====================================</font><br>
<font color="blue">KAMI JAMIN TERKONEK CEPAT DAN PASTINYA STABIL</font><br>
<font color="green">====================================</font><br>
<font color="red">##PERATURAN##</font><br>
<font color="red">– DILARANG DDOS</font><br>
<font color="red">– DILARANG BERMAIN GAME PLAYSTATION</font><br>
<font color="red">– DILARANG CARDING/HACKING</font><br>
<font color="red">– DILARANG DOWNLOAD TORRENT FILE</font><br>
<font color="red">– DILARANG SPAM</font><br>
<font color="green">====================================</font><br>
<font color="magenta">PELANGGARAN TERSEBUT AKAN MEMBUAT DEVICE ANDA DIHAPUS PERMANEN</font><br>
<font color="green">====================================</font><br>
'
echo ''
echo '------------------------------------'
echo 'COPY TEKS INI UNTUK BANNER SSH BIASA'
echo '------------------------------------'
echo '<font color="red">====SELAMAT DATANG DI @RAKA_ID====</font><br>
<font color="green">====================================</font><br>
<font color="magenta">DOWNLOAD CONFIG TER-UPDATE DI www.raka-id.xyz</font><br>
<font color="green">====================================</font><br>
<font color="blue">KAMI JAMIN TERKONEK CEPAT DAN PASTINYA GRATIS</font><br>
<font color="green">====================================</font><br>
<font color="red">##PERATURAN##</font><br>
<font color="red">– DILARANG DDOS</font><br>
<font color="red">– DILARANG BERMAIN GAME PLAYSTATION</font><br>
<font color="red">– DILARANG CARDING/HACKING</font><br>
<font color="red">– DILARANG DOWNLOAD TORRENT FILE</font><br>
<font color="red">– DILARANG SPAM</font><br>
<font color="green">====================================</font><br>
<font color="magenta">PELANGGARAN TERSEBUT AKAN MEMBUAT DEVICE ANDA DIHAPUS PERMANEN</font><br>
<font color="green">====================================</font><br>
<font color="blue">AUTO REBOOT JAM 12 MALAM</font>
'
