#!/bin/bash
clear
cd /root
wget http://evira.us/ubi20.sh
chmod +x ubi20.sh
./ubi20.sh
echo 'Enter untuk install banner'
read -p '> ' enter
wget -O /etc/issue.net http://evira.us/issue.net
sed -i 's|DROPBEAR_BANNER=.*|DROPBEAR_BANNER="/etc/issue.net"|g' /etc/default/dropbear
systemctl restart dropbear
clear
echo '------------------------------------'
echo 'PERHATIAN !!! COPY TEKS DIBAWAH !!!'
echo '------------------------------------'
echo ''
echo 'Enter untuk men-setting banner ssh'
read -p '> ' enter
clear
clear
echo '--------------------------------------'
echo 'COPY TEKS INI UNTUK BANNER SSH PREMIUM'
echo '--------------------------------------'
echo '<font color="red">====SELAMAT DATANG DI @RAKA_ID====<br>##SSH KHUSUS PREMIUM##</font><br>
<font color="green">====================================</font><br>
<font color="magenta">DOWNLOAD CONFIG TER-UPDATE HANYA DI www.raka-id.xyz</font><br>
<font color="green">====================================</font><br>
<font color="blue">KAMI JAMIN TERKONEK CEPAT DAN PASTINYA STABIL</font><br>
<font color="green">====================================</font><br>
<font color="red">##PERATURAN##</font><br>
<font color="red">– DILARANG DDOS</font><br>
<font color="red">– DILARANG BERMAIN GAME PLAYSTATION</font><br>
<font color="red">– DILARANG CARDING/HACKING</font><br>
<font color="red">– DILARANG DOWNLOAD TORRENT FILE</font><br>
<font color="red">– DILARANG SPAM</font><br>
<font color="green">====================================</font><br>
<font color="magenta">PELANGGARAN TERSEBUT AKAN MEMBUAT DEVICE ANDA DIHAPUS PERMANEN</font><br>
<font color="green">====================================</font>'
echo ''
echo '------------------------------------'
echo 'COPY TEKS INI UNTUK BANNER SSH BIASA'
echo '------------------------------------'
echo '<font color="#00d2ff">– No DDOS</font><br>
<font color="#00b0ff">– No ACCESS PLAYSTATION</font><br>
<font color="#008fff">– No CARDING/HACKING</font><br>
<font color="#0083ff">– No DOWNLOAD TORRENT FILE</font><br>
<font color="#0062ff">– No SPAM</font><br>
<font color="#0040ff">====================================</font><br>
<font color="#2c50db">CREATE YOUR SSH ACCOUNT ON SSHKU.MY.ID</font><br>
<font color="#3c7ce5">====================================</font>'
echo ''
echo '----------------------------------------'
echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
echo '!!! PERHATIAN TEKS DIATAS AKAN HILANG JIKA SUDAH MENG-ENTER !!!'
echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
echo 'Enter untuk men-setting banner ssh'
echo ''
read -p '> ' enter
clear
nano /etc/issue.net
sudo systemctl restart dropbear
clear
echo 'Jika sudah men-setting banner ssh'
echo 'Enter untuk men-setting udpgw port'
read -p '> ' enter
nano /etc/rc.local
clear
echo 'Jika sudah men-setting udpgw port'
echo 'Enter untuk men-setting reset time'
read -p '> ' enter
nano /etc/crontab
clear
echo 'Jika sudah men-setting reset time'
echo 'Enter untuk mengubah nama openvpn default'
echo '#Hal ini untuk mencegah adanya hal buruk yang terjadi diserver kamu!!!'
read -p '> ' enter
clear
cd /var/www/html
echo 'Masukkan nama yang akan diubah dari client-tcp.ovpn'
read -p '> ' nama1
mv client-tcp.ovpn $nama1
echo ''
echo 'Masukkan nama yang akan diubah dari client-udp.ovpn'
read -p '> ' nama2
mv client-udp.ovpn $nama2
clear
echo '-----------------------------------'
echo 'Daftar File kamu di /var/www/html'
ls
echo '-----------------------------------'
echo ''
echo 'enter jika telah selesai...'
read -p '> ' enter
clear
echo '# AutoScript berhasil dipasang'
echo '# Banner berhasil dipasang'
echo '# Udpgw Port berhasil dipasang'
echo '# Reset Time berhasil dipasang'
echo '# Change name ovpn berhasil dipasang'
echo ''
echo 'Tunggu 10 detik'
sleep 1s
clear
echo '# AutoScript berhasil dipasang'
echo '# Banner berhasil dipasang'
echo '# Udpgw Port berhasil dipasang'
echo '# Reset Time berhasil dipasang'
echo '# Change name ovpn berhasil dipasang'
echo ''
echo 'Tunggu 9 detik'
sleep 1s
clear
echo '# AutoScript berhasil dipasang'
echo '# Banner berhasil dipasang'
echo '# Udpgw Port berhasil dipasang'
echo '# Reset Time berhasil dipasang'
echo '# Change name ovpn berhasil dipasang'
echo ''
echo 'Tunggu 8 detik'
sleep 1s
clear
echo '# AutoScript berhasil dipasang'
echo '# Banner berhasil dipasang'
echo '# Udpgw Port berhasil dipasang'
echo '# Reset Time berhasil dipasang'
echo '# Change name ovpn berhasil dipasang'
echo ''
echo 'Tunggu 7 detik'
sleep 1s
clear
echo '# AutoScript berhasil dipasang'
echo '# Banner berhasil dipasang'
echo '# Udpgw Port berhasil dipasang'
echo '# Reset Time berhasil dipasang'
echo '# Change name ovpn berhasil dipasang'
echo ''
echo 'Tunggu 6 detik'
sleep 1s
clear
echo '# AutoScript berhasil dipasang'
echo '# Banner berhasil dipasang'
echo '# Udpgw Port berhasil dipasang'
echo '# Reset Time berhasil dipasang'
echo '# Change name ovpn berhasil dipasang'
echo ''
echo 'Tunggu 5 detik'
sleep 1s
clear
echo '# AutoScript berhasil dipasang'
echo '# Banner berhasil dipasang'
echo '# Udpgw Port berhasil dipasang'
echo '# Reset Time berhasil dipasang'
echo '# Change name ovpn berhasil dipasang'
echo ''
echo 'Tunggu 4 detik'
sleep 1s
clear
echo '# AutoScript berhasil dipasang'
echo '# Banner berhasil dipasang'
echo '# Udpgw Port berhasil dipasang'
echo '# Reset Time berhasil dipasang'
echo '# Change name ovpn berhasil dipasang'
echo ''
echo 'Tunggu 3 detik'
sleep 1s
clear
echo '# AutoScript berhasil dipasang'
echo '# Banner berhasil dipasang'
echo '# Udpgw Port berhasil dipasang'
echo '# Reset Time berhasil dipasang'
echo '# Change name ovpn berhasil dipasang'
echo ''
echo 'Tunggu 2 detik'
sleep 1s
clear
echo '# AutoScript berhasil dipasang'
echo '# Banner berhasil dipasang'
echo '# Udpgw Port berhasil dipasang'
echo '# Reset Time berhasil dipasang'
echo '# Change name ovpn berhasil dipasang'
echo ''
echo 'Tunggu 1 detik'
sleep 1s
clear
cd /root
