#!/bin/bash
clear
cd /root
wget http://evira.us/ubi20.sh
chmod +x ubi20.sh
./ubi20.sh
echo '-----------------------'
echo 'Enter untuk install banner'
read -p '> ' enter
wget -O /etc/issue.net http://evira.us/issue.net
sed -i 's|DROPBEAR_BANNER=.*|DROPBEAR_BANNER="/etc/issue.net"|g' /etc/default/dropbear
systemctl restart dropbear
clear
echo '------------------------------------'
echo 'PERHATIAN !!! COPY TEKS DIBAWAH !!!'
echo '------------------------------------'
echo ''
echo 'Enter untuk men-setting banner ssh'
read -p '> ' enter
clear
clear
echo '--------------------------------------'
echo 'COPY TEKS INI UNTUK BANNER SSH PREMIUM'
echo '--------------------------------------'
echo '<font color="red">====SELAMAT DATANG DI @RAKA_ID====<br>##SSH KHUSUS PREMIUM##</font><br>
<font color="green">====================================</font><br>
<font color="magenta">DOWNLOAD CONFIG TER-UPDATE HANYA DI www.raka-id.xyz</font><br>
<font color="green">====================================</font><br>
<font color="blue">KAMI JAMIN TERKONEK CEPAT DAN PASTINYA STABIL</font><br>
<font color="green">====================================</font><br>
<font color="red">##PERATURAN##</font><br>
<font color="red">– DILARANG DDOS</font><br>
<font color="red">– DILARANG BERMAIN GAME PLAYSTATION</font><br>
<font color="red">– DILARANG CARDING/HACKING</font><br>
<font color="red">– DILARANG DOWNLOAD TORRENT FILE</font><br>
<font color="red">– DILARANG SPAM</font><br>
<font color="green">====================================</font><br>
<font color="magenta">PELANGGARAN TERSEBUT AKAN MEMBUAT DEVICE ANDA DIHAPUS PERMANEN</font><br>
<font color="green">====================================</font>'
echo ''
echo '------------------------------------'
echo 'COPY TEKS INI UNTUK BANNER SSH BIASA'
echo '------------------------------------'
echo '<font color="red">====SELAMAT DATANG DI @RAKA_ID====</font><br>
<font color="green">====================================</font><br>
<font color="magenta">DOWNLOAD CONFIG TER-UPDATE DI www.raka-id.xyz</font><br>
<font color="green">====================================</font><br>
<font color="blue">KAMI JAMIN TERKONEK CEPAT DAN PASTINYA GRATIS</font><br>
<font color="green">====================================</font><br>
<font color="red">##PERATURAN##</font><br>
<font color="red">– DILARANG DDOS</font><br>
<font color="red">– DILARANG BERMAIN GAME PLAYSTATION</font><br>
<font color="red">– DILARANG CARDING/HACKING</font><br>
<font color="red">– DILARANG DOWNLOAD TORRENT FILE</font><br>
<font color="red">– DILARANG SPAM</font><br>
<font color="green">====================================</font><br>
<font color="magenta">PELANGGARAN TERSEBUT AKAN MEMBUAT DEVICE ANDA DIHAPUS PERMANEN</font><br>
<font color="green">====================================</font><br>
<font color="blue">AUTO REBOOT JAM 12 MALAM</font>'
echo ''
echo '----------------------------------------'
echo 'Jika sudah meng-copy teks diatas'
echo 'Enter untuk men-setting banner ssh'
echo '!!! PERHATIAN TEKS DIATAS AKAN HILANG JIKA SUDAH MENG-ENTER !!!'
read -p '> ' enter
clear
nano /etc/issue.net
clear
echo 'Jika sudah men-setting banner ssh'
echo 'Enter untuk men-setting udpgw port'
read -p '> ' enter
nano /etc/rc.local
clear
echo 'Jika sudah men-setting udpgw port'
echo 'Enter untuk mengubah nama openvpn default'
echo '#Hal ini untuk mencegah adanya hal buruk yang terjadi diserver kamu!!!'
read -p '> ' enter
cd /var/www/html
clear
ls
