#!/bin/bash
clear
echo "	Tools untuk install ovpn,usrbin,dan copy"
echo "	__________________________________________"
echo ""
echo "Daftar Menu :"
echo "1. Install ovpn"
echo "2. Install usrbin"
echo "3. Install copy"
echo "4. Install semuanya"
echo "5. Exit"
echo ""
read -p "-> " jawaban
if [ $jawaban == 1 ]
then
cd /root
wget https://raw.githack.com/rakhanayottama1234/bahan/main/installovpn
chmod +x installovpn
bash installovpn
echo "#ovpn berhasil dipasang#"
read -p "enter untuk kembali" enter
bash installall
fi
if [ $jawaban == 2 ]
then
cd /root
wget https://raw.githack.com/rakhanayottama1234/bahan/main/usrbin
chmod +x usrbin
mv usrbin /usr/bin
echo "#usrbin berhasil dipasang"
echo "ketik usrbin untuk membuka tools"
echo ''
read -p 'enter untuk kembali' enter
bash installall
fi
if [ $jawaban == 3 ]
then
wget https://raw.githack.com/rakhanayottama1234/bahan/main/copy
chmod +x copy
mv copy /usr/bin
echo "ketik copy untuk membuka tools"
read -p "enter untuk kembali"
fi
if [ $jawaban == 4 ]
then
cd /root
wget https://raw.githack.com/rakhanayottama1234/bahan/main/installovpn
chmod +x installovpn
bash installovpn
cd /root
wget https://raw.githack.com/rakhanayottama1234/bahan/main/usrbin
chmod +x usrbin
mv usrbin /usr/bin
echo "#usrbin berhasil dipasang"
echo "ketik usrbin untuk membuka tools"
echo ''
read -p 'enter untuk kembali' enter
wget https://raw.githack.com/rakhanayottama1234/bahan/main/copy
chmod +x copy
mv copy /usr/bin
echo "ketik copy untuk membuka tools"
read -p "enter untuk kembali"
fi
if [ $jawaban == 5 ]
then
clear
exit
fi
