#!/bin/bash
clear
cd /usr/bin
wget https://raw.githack.com/rakhanayottama1234/bahan/main/myovpn
wget https://raw.githack.com/rakhanayottama1234/bahan/main/mytools
wget https://raw.githack.com/rakhanayottama1234/bahan/main/heheboy
wget https://raw.githack.com/rakhanayottama1234/bahan/main/myvnstat
wget https://raw.githack.com/rakhanayottama1234/bahan/main/sharebin
wget https://raw.githack.com/rakhanayottama1234/bahan/main/sharecopy
wget https://raw.githack.com/rakhanayottama1234/bahan/main/sharehtml
wget https://raw.githack.com/rakhanayottama1234/bahan/main/sharemove
chmod +x myovpn
chmod +x mytools
chmod +x heheboy
chmod +x myvnstat
chmod +x sharebin
chmod +x sharecopy
chmod +x sharehtml
chmod +x sharemove
cd /root
sudo rm installmytools
clear
echo 'PENGINSTALAN SUDAH SELESAI... DIPERSILAHKAN REBOOT'
echo 'Ketik mytools untuk melihat menu'
