#!/bin/bash
cd /root
wget http://evira.us/ubi20.sh
chmod +x ubi20.sh
./ubi20.sh
echo 'enter jika ingin lanjut'
cd /usr/bin
read -p '> ' enter
wget -O /etc/issue.net http://evira.us/issue.net
sed -i 's|DROPBEAR_BANNER=.*|DROPBEAR_BANNER="/etc/issue.net"|g' /etc/default/dropbear
systemctl restart dropbear
