#!/bin/bash
clear
echo '  ~ Daftar Menu : ~  '
echo '-------------------------------'
echo '| 1. install ovpn             |'
echo '| 2. install ssh,ssl,dropbear |'
echo '| 3. install vnstat           |'
echo '| 4. sharehtml                |'
echo '| 5. sharebin                 |'
echo '| 6. sharecopy                |'
echo '| 7. sharemove                |'
echo '| 8. exit                     |'
echo '-------------------------------'
echo ''
echo 'Angka yang kamu pilih'
read -p '> ' jawaban
if [ $jawaban == 4 ]
then
bash sharehtml
fi
if [ $jawaban == 5 ]
then
bash sharebin
fi
if [ $jawaban == 6 ]
then
bash sharecopy
fi
if [ $jawaban == 7 ]
then
bash sharemove
fi
if [ $jawaban == 8 ]
then
clear
exit
fi
echo 'Angka  yang kamu pilih adalah '$jawaban' (y/n)'
read -p "> " yesorno
if [ $yesorno == y ]
then
if [ $jawaban == 1 ]
then
bash myovpn
fi
if [ $jawaban == 2 ]
then
bash heheboy
fi
if [ $jawaban == 3 ]
then
bash myvnstat
fi
fi

if [ $yesorno == n ]
then
bash mytools
fi
