#!/bin/bash
clear
echo '       ~ Daftar Menu : ~     '
echo '---------------------------------------'
echo '| 1. install ovpn                     |'
echo '| 2. install AutoScrript Ubuntu 20.04 |'
echo '| 3. install AutoScrript Debian 10    |'
echo '| 4. install vnstat                   |'
echo '| 5. sharehtml                        |'
echo '| 6. sharebin                         |'
echo '| 7. sharecopy                        |'
echo '| 8. sharemove                        |'
echo '| 9. exit                             |'
echo '---------------------------------------'
echo ''
echo 'Angka yang kamu pilih'
read -p '> ' jawaban
if [ $jawaban == 4 ]
then
bash sharehtml
fi
if [ $jawaban == 5 ]
then
bash sharebin
fi
if [ $jawaban == 6 ]
then
bash sharecopy
fi
if [ $jawaban == 7 ]
then
bash sharemove
fi
if [ $jawaban == 8 ]
then
clear
exit
fi
echo 'Angka  yang kamu pilih adalah '$jawaban' (y/n)'
read -p "> " yesorno
if [ $yesorno == y ]
then
if [ $jawaban == 1 ]
then
bash myovpn
fi
if [ $jawaban == 2 ]
then
bash heheboyubi20
fi
if [ $jawaban == 3 ]
then
bash heheboydeb10
fi
if [ $jawaban == 4 ]
then
bash myvnstat
fi
fi

if [ $yesorno == n ]
then
bash mytools
fi
