#!/bin/bash
clear
echo '  ~ Daftar Menu : ~  '
echo '  ----------------------  '
echo '1. ovpn'
echo '2. sharehtml'
echo '3. sharebin'
echo '4. sharecopy'
echo '5. sharemove'
echo '6. ssh,ssl,dropbear'
echo '7. exit'
echo '  ----------------------  '
echo ''
echo ' Angka yang kamu pilih'
read -p '> ' jawaban
if [ $jawaban == 7 ]
then
clear
exit
fi
echo 'Angka  yang kamu pilih adalah '$jawaban' (y/n)'
read -p "> " yesorno
if [ $yesorno == y ]
then
if [ $jawaban == 1 ]
then
bash myovpn
fi
if [ $jawaban == 2 ]
then
bash sharehtml
fi
if [ $jawaban == 3 ]
then
bash sharebin
fi
if [ $jawaban == 4 ]
then
bash sharecopy
fi
if [ $jawaban == 5 ]
then
bash sharemove
fi
if [ $jawaban == 6 ]
then
bash menu
fi
fi

if [ $yesorno == n ]
then
bash mytools
fi
