#!/bin/bash
clear
apt install vnstat
systemctl restart vnstat
cd /root
systemctl restart vnstat
clear
echo 'vnstat berhasil dipasang'
read -p 'enter enter enter' enter
clear
sudo systemctl restart vnstat
