#!/bin/bash
clear
echo "Selamat Datang di tools kami."
echo "1. move to usrbin"
echo "2. exit"
read -p "> " jawaban
if [ $jawaban == 1 ]
then
clear
echo "#######"
ls
echo "#######"
echo ""
echo "masukkan file yang ingin kamu pindah"
read -p "> " code
echo ""
clear
echo "file *$code* akan segera kami pindah"
mv $code /usr/bin
echo "tekan enter untuk melanjutkan"
echo ""
read -p "enter... enter... enter..." enter
clear
echo ""
echo "00000000000"
echo "- pemindahan selesai :)"
cd /usr/bin
chmod +x $code
echo "- proses chmod selesai"
echo "- file aman"
echo "- file tidak corrupt"
echo "00000000000"
echo ""
echo "####__ terimakasih __####"
echo ""
fi
if [ $jawaban == 2 ]
then
clear
exit
fi
